package e2e

import (
	"fmt"
	"sync"
)

type NetworkAllocator struct {
	mu      sync.Mutex
	counter int
}

var GlobalNetworkAllocator = &NetworkAllocator{}

// Allocate returns a unique subnet and gateway for a test run.
// It assumes a base network of 172.20.0.0/16 and hands out /24 subnets.
// e.g. 0 -> 172.20.0.0/24 (Gateway 172.20.0.1)
//
//	1 -> 172.20.1.0/24 (Gateway 172.20.1.1)
func (s *NetworkAllocator) Allocate() (string, string) {
	s.mu.Lock()
	defer s.mu.Unlock()

	idx := s.counter
	s.counter++

	subnet := fmt.Sprintf("172.20.%d.0/24", idx)
	gateway := fmt.Sprintf("172.20.%d.1", idx)

	return subnet, gateway
}

// GetIP returns an IP address within the allocated subnet for a given host suffix.
// subnet is expected to be in "172.20.x.0/24" format.
// suffix is the last octet (e.g. 10).
func GetIP(subnet string, suffix int) string {
	// Simple parsing, assuming the format generated by Allocate
	// subnet: 172.20.x.0/24
	base := subnet[:len(subnet)-4] // remove /24
	// base: 172.20.x.0
	// we want 172.20.x.<suffix>

	// find the last dot
	lastDot := -1
	for i := len(base) - 1; i >= 0; i-- {
		if base[i] == '.' {
			lastDot = i
			break
		}
	}

	if lastDot == -1 {
		panic(fmt.Sprintf("invalid subnet format: %s", subnet))
	}

	prefix := base[:lastDot+1] // 172.20.x.
	return fmt.Sprintf("%s%d", prefix, suffix)
}
