# .github/workflows/release.yaml

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  release-unix:
    name: Release Go Binary (Unix)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
  release-windows:
    name: Release Go Binary (Windows) # Windows requires the wintun driver, so we use a separate action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ windows ]
        goarch: [ amd64, arm64 ]
        wintun_version: [ 0.14.1 ]
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          pre_command: 'wget https://www.wintun.net/builds/wintun-${{ matrix.wintun_version }}.zip && unzip wintun-${{ matrix.wintun_version }}.zip'
          extra_files: 'wintun/bin/${{ matrix.goarch }}/wintun.dll'